#!/bin/sh

SCRIPTS_ENABLED_DIR=~/.local/share/desktopd/scripts-enabled

mkdir -p $SCRIPTS_ENABLED_DIR
ln -sf /usr/share/desktopd/scripts/kde-InsertDesktop $SCRIPTS_ENABLED_DIR/InsertDesktop
ln -sf /usr/share/desktopd/scripts/kde-NumberOfDesktops $SCRIPTS_ENABLED_DIR/NumberOfDesktops
ln -sf /usr/share/desktopd/scripts/kde-CurrentDesktop $SCRIPTS_ENABLED_DIR/CurrentDesktop

